/**Parametro dados monitorados*/

CREATE TABLE hospitais.APPHOSP_DADOS_MONIT_PARAM (
  ID_PARAMETRO NUMBER NOT NULL,  
  DS_PARAMETRO VARCHAR(100) NOT NULL,
  DS_UNIDADE_MEDIDA VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_PARAMETRO)
);

  CREATE SEQUENCE hospitais.APPHOSP_DADOS_MONIT_PARAM_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999       
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
  
  CREATE OR REPLACE TRIGGER hospitais.APPHOSP_DADOS_MONIT_PARAM_TRG 
  BEFORE INSERT ON hospitais.APPHOSP_DADOS_MONIT_PARAM
  FOR EACH ROW
BEGIN
  SELECT hospitais.APPHOSP_DADOS_MONIT_PARAM_SEQ.NEXTVAL 
  INTO :NEW.ID_PARAMETRO 
  FROM DUAL;
END; 

GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PARAM TO hospitais
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PARAM TO hospitaisusr

/**Valor dados monitorados*/

CREATE TABLE hospitais.APPHOSP_DADOS_MONITORADOS (
  ID_DADOS_MONITORADOS NUMBER NOT NULL,
  ID_PARAMETRO NUMBER NOT NULL,
  ID_USUARIO NUMBER NOT NULL,
  VALOR VARCHAR(100) NOT NULL, 
  COMENTARIO VARCHAR(200)
  DT_CRIACAO DATE NOT NULL,
  FL_ATIVO NUMBER(1) NOT NULL,
  DT_EXCLUSAO DATE,
  PRIMARY KEY (ID_DADOS_MONITORADOS),
  CONSTRAINT FK_DADOS_MONIT_PARAM_VAL FOREIGN KEY(ID_PARAMETRO) REFERENCES hospitais.APPHOSP_DADOS_MONIT_PARAM(ID_PARAMETRO),
  CONSTRAINT FK_DADOS_MONIT_USER FOREIGN KEY(ID_USUARIO) REFERENCES hospitais.APPHOSP_USUARIO(ID_USUARIO)
);

  CREATE SEQUENCE hospitais.APPHOSP_DADOS_MONITORADOS_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999       
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
  
  CREATE OR REPLACE TRIGGER hospitais.APPHOSP_DADOS_MONITORADOS_TRG 
  BEFORE INSERT ON hospitais.APPHOSP_DADOS_MONITORADOS
  FOR EACH ROW
BEGIN
  SELECT hospitais.APPHOSP_DADOS_MONITORADOS_SEQ.NEXTVAL 
  INTO :NEW.ID_DADOS_MONITORADOS 
  FROM DUAL;
END; 

GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONITORADOS TO hospitais
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONITORADOS TO hospitaisusr
