INSERT INTO hospitais.APPHOSP_DADOS_MONIT_PARAM(DS_PARAMETRO, DS_UNIDADE_MEDIDA) VALUES('Peso','kg')
/
INSERT INTO hospitais.APPHOSP_DADOS_MONIT_PARAM(DS_PARAMETRO, DS_UNIDADE_MEDIDA) VALUES('Batimento cardíaco','Bpm')
/
INSERT INTO hospitais.APPHOSP_DADOS_MONIT_PARAM(DS_PARAMETRO, DS_UNIDADE_MEDIDA) VALUES('Pressão arterial','mmHg')
/
INSERT INTO hospitais.APPHOSP_DADOS_MONIT_PARAM(DS_PARAMETRO, DS_UNIDADE_MEDIDA) VALUES('Saturação de Oxigênio','%')
/
INSERT INTO hospitais.APPHOSP_DADOS_MONIT_PARAM(DS_PARAMETRO, DS_UNIDADE_MEDIDA) VALUES('Glicose no sangue','mg/dL')
/
COMMIT