
-- Amesp
create user AMESPUSR
  default tablespace TBSASM_DATA
  temporary tablespace TEMP
  profile DEFAULT
  identified by "AMESPUSR#2018"
  account lock;
/
grant create any table to AMESPUSR;
/
grant drop any table to AMESPUSR;
/
grant unlimited tablespace to AMESPUSR; 
/
create user AMESPUSRH
  default tablespace TBSASM_DATA
  temporary tablespace TEMP
  profile DEFAULT
  identified by "AMESPUSRH#2018"
  account lock;
/
grant create any table to AMESPUSRH;
/
grant drop any table to AMESPUSRH;
/
grant unlimited tablespace to AMESPUSRH; 
/
CREATE ROLE AMESP_ROLE
/
ALTER USER AMESPUSR DEFAULT TABLESPACE TBSASM_DATA
/
ALTER USER AMESPUSR QUOTA UNLIMITED ON TBSASM_DATA
/
ALTER USER AMESPUSR QUOTA UNLIMITED ON TBSASM_INDEX
/
GRANT CREATE SESSION TO AMESPUSR
/
ALTER USER AMESPUSRH DEFAULT TABLESPACE TBSASM_DATA
/
ALTER USER AMESPUSRH QUOTA UNLIMITED ON TBSASM_DATA
/
ALTER USER AMESPUSRH QUOTA UNLIMITED ON TBSASM_INDEX
/
GRANT CREATE SESSION TO AMESPUSRH
/
GRANT AMESP_ROLE TO AMESPUSR
/
GRANT AMESP_ROLE TO AMESPUSRH
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.AA_ESPECIALIDADES TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.ACESSO_LOGIN TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.ACESSO_CHAVE_ATIVACAO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.ACESSO_SISTEMA_VERSOES TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.CM_BASE_DADOS_WPD TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.CM_ESCALA_RISCO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.CM_ESTRATIFICACAO_RISCO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.CM_FILIAL TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.ESTADOS TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.GLB_FUSO_HORARIO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.CM_FILIAL_UF TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.CM_REGIONAL TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.GLB_CONFIG_DATABASE TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.INI_CONFIG TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE_FASE TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE_FASE_PERIODO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_CONTAGEM_PACIENTES TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_ESPECIALIDADES TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE_DIVISAO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE_ESPECIALIDADE TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_ESPECIALIDADE_DIVISAO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_FASE_SUMARIO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_FEEDBACK_PACIENTE TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_GRUPO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_GRUPO_UNIDADE TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_TEMPO_ESPEC_RISCO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_TEMPO_FASE_RISCO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE_FASE_ESPEC TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE_FASE_SUMARIO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.NOW_UNIDADE_USUARIO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.WF_HISTORICO TO AMESP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON AMESP.PROFISSIONAL_SAUDE_PROPRIO TO AMESP_ROLE
/
