--Criação de View apos criação do owner hospitais e amesp


 CREATE OR REPLACE FORCE VIEW "HOSPITAIS"."HSP_TEMPO_ESPEC_RISCO" ("ID_UNIDADE", "ID_CHAVE_ESPECIALIDADE", "CODIGO", "QT_MINUTOS_ESTIMATIVA") AS 
  SELECT ID_UNIDADE,
       ID_CHAVE_ESPECIALIDADE,
       CODIGO,
       CASE
         WHEN NVL(MAX(qt_minutos_maximo_azul), 0) > 0 THEN
          MAX(qt_minutos_maximo_azul)
         ELSE
          MAX(qt_minutos_maximo_semrisco)
       END AS QT_MINUTOS_ESTIMATIVA

  FROM (SELECT B.ID_UNIDADE,
               B.ID_CHAVE_ESPECIALIDADE,
               E.CODIGO,
               FIRST_VALUE(A.QT_MINUTOS_ESTIMATIVA) OVER(PARTITION BY B.ID_UNIDADE, B.ID_CHAVE_ESPECIALIDADE, E.CODIGO ORDER BY NVL(id_risco, 0)) qt_minutos_maximo_semrisco,
               FIRST_VALUE(A.QT_MINUTOS_ESTIMATIVA) OVER(PARTITION BY B.ID_UNIDADE, B.ID_CHAVE_ESPECIALIDADE, E.CODIGO ORDER BY NVL(id_risco, 99)) qt_minutos_maximo_azul
          FROM AMESP.NOW_TEMPO_ESPEC_RISCO A
         INNER JOIN AMESP.NOW_UNIDADE_ESPECIALIDADE B
            ON A.ID_UNIDADE_ESPECIALIDADE = B.ID_UNIDADE_ESPECIALIDADE
         INNER JOIN AMESP.AA_ESPECIALIDADES E
            ON B.ID_CHAVE_ESPECIALIDADE = E.ID_CHAVE)
 GROUP BY ID_UNIDADE, ID_CHAVE_ESPECIALIDADE, CODIGO;