
-- Amesp
create user SGPUSR
  default tablespace TBSASM_DATA
  temporary tablespace TEMP
  profile DEFAULT
  identified by "SGPUSR#2018"
  account lock;
/
grant create any table to SGPUSR;
/
grant drop any table to SGPUSR;
/
grant unlimited tablespace to SGPUSR; 
/
create user SGPUSRH
  default tablespace TBSASM_DATA
  temporary tablespace TEMP
  profile DEFAULT
  identified by "SGPUSRH#2018"
  account lock;
/
grant create any table to SGPUSRH;
/
grant drop any table to SGPUSRH;
/
grant unlimited tablespace to SGPUSRH; 
/
CREATE ROLE SGP_ROLE
/
ALTER USER SGPUSR DEFAULT TABLESPACE TBSASM_DATA
/
ALTER USER SGPUSR QUOTA UNLIMITED ON TBSASM_DATA
/
ALTER USER SGPUSR QUOTA UNLIMITED ON TBSASM_INDEX
/
GRANT CREATE SESSION TO SGPUSR
/
ALTER USER SGPUSRH DEFAULT TABLESPACE TBSASM_DATA
/
ALTER USER SGPUSRH QUOTA UNLIMITED ON TBSASM_DATA
/
ALTER USER SGPUSRH QUOTA UNLIMITED ON TBSASM_INDEX
/
GRANT CREATE SESSION TO SGPUSRH
/
GRANT SGP_ROLE TO SGPUSR
/
GRANT SGP_ROLE TO SGPUSRH
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.CONFIGURACAO_SISTEMA_SGP TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.CURSO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.UNIDADE TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_SENHA TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.EMAIL_TOKEN TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.ESPECIALIDADE TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.SUBSETOR TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.SETOR TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.SETOR_SUBSETOR TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.GRUPO_QUALIDADE TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.JUSTIFICATIVA TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.TURNO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.UNIDADE_CONTATO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.UNIDADE_ENDERECO_PLANTAO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PLANTAO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PLANTAO_OFERTA TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PLANTAO_OFERTA_PROFISSIONAL TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.OFERTA_COMUNICADO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PLANTAO_PROFISSIONAL TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PLANTAO_BLOQUEIO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PLANTAO_BLOQUEIO_DIA_SEMANA TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PLANTAO_PROF_DIA_SEMANA TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_COMENTARIO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_CONSELHO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_CONTATO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_CURSO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_EMAIL TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_ESPECIALIDADE TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_EXCECOES TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROFISSIONAL_GRUPO_QUALIDADE TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.PROF_GRUPO_QUALIDADE_HIST TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.TURNO_CONFIGURACAO TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.UNIDADE_CONTATO_TELEFONE TO SGP_ROLE
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SGP.USUARIO_UNIDADE TO SGP_ROLE