//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amil.AsmWebCad.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amil.AsmWebCad.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso Negado !.
        /// </summary>
        public static string AcessoNegado {
            get {
                return ResourceManager.GetString("AcessoNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Acoes {
            get {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Código de corporativo&apos; deve ter no máximo 10 caracteres..
        /// </summary>
        public static string AlertaCodigoIntegracaoMax {
            get {
                return ResourceManager.GetString("AlertaCodigoIntegracaoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Codigo&apos; deve ter no máximo 50 caracteres..
        /// </summary>
        public static string AlertaCodigoMax50 {
            get {
                return ResourceManager.GetString("AlertaCodigoMax50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Confirmação de login deve ser igual ao Login..
        /// </summary>
        public static string AlertaConfirmacaoDiferente {
            get {
                return ResourceManager.GetString("AlertaConfirmacaoDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome da divisão..
        /// </summary>
        public static string AlertaDivisao {
            get {
                return ResourceManager.GetString("AlertaDivisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Login&apos; deve ter no máximo 50 caracteres..
        /// </summary>
        public static string AlertaLoginMax50 {
            get {
                return ResourceManager.GetString("AlertaLoginMax50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite ao menos 3 caracteres para efetuar a pesquisa..
        /// </summary>
        public static string AlertaNome3Caracteres {
            get {
                return ResourceManager.GetString("AlertaNome3Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Nome&apos; deve ter no máximo 60 caracteres..
        /// </summary>
        public static string AlertaNomeMax60 {
            get {
                return ResourceManager.GetString("AlertaNomeMax60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Perfil&apos; deve ter no máximo 100 caracteres..
        /// </summary>
        public static string AlertaPerfilMax100 {
            get {
                return ResourceManager.GetString("AlertaPerfilMax100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Senha&apos; deve ter no máximo 10 caracteres..
        /// </summary>
        public static string AlertaSenhaMax10 {
            get {
                return ResourceManager.GetString("AlertaSenhaMax10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha algum campo para realizar a pesquisa!.
        /// </summary>
        public static string AlertaTelaPesquisaUsuariosCampos {
            get {
                return ResourceManager.GetString("AlertaTelaPesquisaUsuariosCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar senha.
        /// </summary>
        public static string AlterarSenha {
            get {
                return ResourceManager.GetString("AlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de senha.
        /// </summary>
        public static string AlteraSenha_Titulo {
            get {
                return ResourceManager.GetString("AlteraSenha_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Usuário.
        /// </summary>
        public static string AssociarPerfil {
            get {
                return ResourceManager.GetString("AssociarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bom Dia.
        /// </summary>
        public static string BomDia {
            get {
                return ResourceManager.GetString("BomDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Usuários.
        /// </summary>
        public static string Cadastro_Usuarios {
            get {
                return ResourceManager.GetString("Cadastro_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório.
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Base.
        /// </summary>
        public static string CodigoBase {
            get {
                return ResourceManager.GetString("CodigoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Corporativo.
        /// </summary>
        public static string CodigoCorporativo {
            get {
                return ResourceManager.GetString("CodigoCorporativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmaçao da nova senha.
        /// </summary>
        public static string ConfirmacaoNovaSenha {
            get {
                return ResourceManager.GetString("ConfirmacaoNovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar E-mail.
        /// </summary>
        public static string ConfirmarEmail {
            get {
                return ResourceManager.GetString("ConfirmarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Login.
        /// </summary>
        public static string ConfirmarLogin {
            get {
                return ResourceManager.GetString("ConfirmarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve conter Letras Maiúsculas, Minúsculas, Números, Caracteres Especiais e tamanho mínimo deve ser de 8 caracteres..
        /// </summary>
        public static string ControleSenha {
            get {
                return ResourceManager.GetString("ControleSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido.
        /// </summary>
        public static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string DataNascimento {
            get {
                return ResourceManager.GetString("DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string DescricaoBloqueado {
            get {
                return ResourceManager.GetString("DescricaoBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail cadastrado.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não cadastrado!.
        /// </summary>
        public static string EmailNaoCadastrado {
            get {
                return ResourceManager.GetString("EmailNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mails digitados não conferem!.
        /// </summary>
        public static string EmailsNaoConferem {
            get {
                return ResourceManager.GetString("EmailsNaoConferem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala de Risco.
        /// </summary>
        public static string EscalaRisco {
            get {
                return ResourceManager.GetString("EscalaRisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade.
        /// </summary>
        public static string EspecialidadeNow {
            get {
                return ResourceManager.GetString("EspecialidadeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidades Now.
        /// </summary>
        public static string EspecialidadesNow {
            get {
                return ResourceManager.GetString("EspecialidadesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha.
        /// </summary>
        public static string EsqueciMinhaSenha {
            get {
                return ResourceManager.GetString("EsqueciMinhaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha.
        /// </summary>
        public static string EsqueciSenha_Mensagem {
            get {
                return ResourceManager.GetString("EsqueciSenha_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha.
        /// </summary>
        public static string EsqueciSenha_Titulo {
            get {
                return ResourceManager.GetString("EsqueciSenha_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string Inativo {
            get {
                return ResourceManager.GetString("Inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string Limpar {
            get {
                return ResourceManager.GetString("Limpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Especialidades.
        /// </summary>
        public static string ListaEspecialidades {
            get {
                return ResourceManager.GetString("ListaEspecialidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Unidades.
        /// </summary>
        public static string ListaUnidades {
            get {
                return ResourceManager.GetString("ListaUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Divisões por Unidade.
        /// </summary>
        public static string ListaUnidadesDivisao {
            get {
                return ResourceManager.GetString("ListaUnidadesDivisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Titulo {
            get {
                return ResourceManager.GetString("Login_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou Senha inválidos.
        /// </summary>
        public static string LoginNaoEncontrado {
            get {
                return ResourceManager.GetString("LoginNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon de acesso.
        /// </summary>
        public static string LogonAcesso {
            get {
                return ResourceManager.GetString("LogonAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o registro?.
        /// </summary>
        public static string MensagemConfirmacaoExclusao {
            get {
                return ResourceManager.GetString("MensagemConfirmacaoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir #?.
        /// </summary>
        public static string MensagemConfirmacaoExclusaoEditavel {
            get {
                return ResourceManager.GetString("MensagemConfirmacaoExclusaoEditavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a descrição da Perfil que deseja buscar.
        /// </summary>
        public static string MensagemFiltroPerfildeviso {
            get {
                return ResourceManager.GetString("MensagemFiltroPerfildeviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo Número Conselho para prosseguir.
        /// </summary>
        public static string MensagemNumeroConselho {
            get {
                return ResourceManager.GetString("MensagemNumeroConselho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome do Perfil que deseja buscar.
        /// </summary>
        public static string MensagemPreenchaNome {
            get {
                return ResourceManager.GetString("MensagemPreenchaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Sistema para efetuar a pesquisa..
        /// </summary>
        public static string MensagemPreenchaSistema {
            get {
                return ResourceManager.GetString("MensagemPreenchaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído com sucesso!.
        /// </summary>
        public static string MensagemSucessoExclusao {
            get {
                return ResourceManager.GetString("MensagemSucessoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro gravado com sucesso!.
        /// </summary>
        public static string MensagemSucessoGravacao {
            get {
                return ResourceManager.GetString("MensagemSucessoGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo Tipo Conselho para prosseguir.
        /// </summary>
        public static string MensagemTipoConselho {
            get {
                return ResourceManager.GetString("MensagemTipoConselho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo UF para prosseguir.
        /// </summary>
        public static string MensagemUF {
            get {
                return ResourceManager.GetString("MensagemUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar esta operação. Tente novamente mais tarde!.
        /// </summary>
        public static string NaoFoiPossivelRealizarOperacao {
            get {
                return ResourceManager.GetString("NaoFoiPossivelRealizarOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de Configuração Americas.
        /// </summary>
        public static string NomePortal {
            get {
                return ResourceManager.GetString("NomePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string NovaSenha {
            get {
                return ResourceManager.GetString("NovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Perfil.
        /// </summary>
        public static string Perfil_Titulo {
            get {
                return ResourceManager.GetString("Perfil_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Pesquisa {
            get {
                return ResourceManager.GetString("Pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Especialidade Now.
        /// </summary>
        public static string PesquisaEspecialidade {
            get {
                return ResourceManager.GetString("PesquisaEspecialidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Perfil.
        /// </summary>
        public static string PesquisaPerfil {
            get {
                return ResourceManager.GetString("PesquisaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por.
        /// </summary>
        public static string PesquisarPor {
            get {
                return ResourceManager.GetString("PesquisarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional.
        /// </summary>
        public static string Regional {
            get {
                return ResourceManager.GetString("Regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string Selecione {
            get {
                return ResourceManager.GetString("Selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas digitadas não conferem!.
        /// </summary>
        public static string SenhaDigitadasNaoConferem {
            get {
                return ResourceManager.GetString("SenhaDigitadasNaoConferem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha enviada para.
        /// </summary>
        public static string SenhaEnviada {
            get {
                return ResourceManager.GetString("SenhaEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string Sigla {
            get {
                return ResourceManager.GetString("Sigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string SimboloExcluirSelecao {
            get {
                return ResourceManager.GetString("SimboloExcluirSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string SimboloExcluirSelecaoTodos {
            get {
                return ResourceManager.GetString("SimboloExcluirSelecaoTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string SimboloIncluirSelecao {
            get {
                return ResourceManager.GetString("SimboloIncluirSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string SimboloSelecionarTodos {
            get {
                return ResourceManager.GetString("SimboloSelecionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string Sistema {
            get {
                return ResourceManager.GetString("Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String1.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurador WEB ASM.
        /// </summary>
        public static string Titulo_CadWeb {
            get {
                return ResourceManager.GetString("Titulo_CadWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string TituloBotaoAnterior {
            get {
                return ResourceManager.GetString("TituloBotaoAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar campos.
        /// </summary>
        public static string TituloBotaoLimpar {
            get {
                return ResourceManager.GetString("TituloBotaoLimpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associar Módulos.
        /// </summary>
        public static string TituloBotaoModuloPerfil {
            get {
                return ResourceManager.GetString("TituloBotaoModuloPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir novo registro.
        /// </summary>
        public static string TituloBotaoNovo {
            get {
                return ResourceManager.GetString("TituloBotaoNovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string TituloBotaoPesquisar {
            get {
                return ResourceManager.GetString("TituloBotaoPesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string TituloBotaoSalvar {
            get {
                return ResourceManager.GetString("TituloBotaoSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string TituloBotaoVoltar {
            get {
                return ResourceManager.GetString("TituloBotaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir selecionados.
        /// </summary>
        public static string TituloExcluirSelecao {
            get {
                return ResourceManager.GetString("TituloExcluirSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir todos selecionados.
        /// </summary>
        public static string TituloExcluirSelecaoTodos {
            get {
                return ResourceManager.GetString("TituloExcluirSelecaoTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade Now.
        /// </summary>
        public static string TituloFormDadosEspecialidadeNow {
            get {
                return ResourceManager.GetString("TituloFormDadosEspecialidadeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Perfil.
        /// </summary>
        public static string TituloFormDadosPerfil {
            get {
                return ResourceManager.GetString("TituloFormDadosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Unidade.
        /// </summary>
        public static string TituloFormDadosUnidade {
            get {
                return ResourceManager.GetString("TituloFormDadosUnidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Usuário.
        /// </summary>
        public static string TituloFormDadosUsuario {
            get {
                return ResourceManager.GetString("TituloFormDadosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir selecionados.
        /// </summary>
        public static string TituloIncluirSelecao {
            get {
                return ResourceManager.GetString("TituloIncluirSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar todos.
        /// </summary>
        public static string TituloSelecionarTodos {
            get {
                return ResourceManager.GetString("TituloSelecionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string UF {
            get {
                return ResourceManager.GetString("UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades Now.
        /// </summary>
        public static string UnidadesNow {
            get {
                return ResourceManager.GetString("UnidadesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Unidade.
        /// </summary>
        public static string UnidadeTitulo {
            get {
                return ResourceManager.GetString("UnidadeTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario_Titulo {
            get {
                return ResourceManager.GetString("Usuario_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado!.
        /// </summary>
        public static string UsuarioBloqueado {
            get {
                return ResourceManager.GetString("UsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externo.
        /// </summary>
        public static string UsuarioExterno {
            get {
                return ResourceManager.GetString("UsuarioExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inativo.
        /// </summary>
        public static string UsuarioInativo {
            get {
                return ResourceManager.GetString("UsuarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interno.
        /// </summary>
        public static string UsuarioInterno {
            get {
                return ResourceManager.GetString("UsuarioInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário sem perfil ao sistema.
        /// </summary>
        public static string UsuarioSemPerfil {
            get {
                return ResourceManager.GetString("UsuarioSemPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou Senha inválidos.
        /// </summary>
        public static string UsuarioSenhaInvalidos {
            get {
                return ResourceManager.GetString("UsuarioSenhaInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string UsuarioTipo {
            get {
                return ResourceManager.GetString("UsuarioTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha antiga não pode ser igual a senha nova.
        /// </summary>
        public static string ValidarSenhaAntigaComNova {
            get {
                return ResourceManager.GetString("ValidarSenhaAntigaComNova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
    }
}
